services:
  db:
    container_name: sales-bot-db
    image: postgres:15-alpine
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sales-bot-network

volumes:
  postgres_data:

networks:
  sales-bot-network:
    driver: bridge